name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Authenticating to Team Berry's GitHub Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.REGISTRY_KEY }}" >> ~/.npmrc
      - name: Publish
        run: npm publish